version: "3.9"

services:
  stride-api:
    build: .
    container_name: stride-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - stride-db
    volumes:
      - ./Logs:/app/Logs
      - ./Models:/app/Models

  stride-db:
    image: postgres:16
    container_name: stride-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - stride-db-data:/var/lib/postgresql/data

volumes:
  stride-db-data:
